version: '2'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  lbapp:
    image: dockercloud/haproxy
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
  app:
    image: odisei/my-simple-node
    expose:
      - "1337"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/test
volumes:
  mongo-data: